### ISSUE TITLE
`5.1.1.0` release checklist

### ISSUE THREAD

**Issue by Anut-py** [Anut-py/h-raylib#43]
- Documentation
    - [x] Update README.md
    - [x] Update DOCUMENTATION.md
    - [x] Update CHANGELOG.md
    - [x] Update CONTRIBUTING.md
    - [x] Check Haddock documentation for completeness
- Submodules
    - [x] Update raylib
    - [x] Update raygui
    - New submodules
        - [x] Add to cabal config
        - [x] Add to nix config
        - [x] Add to devtools.js
        - [x] Create example
    - New structures
        - [x] Add to Raylib.Util.Lenses
- General
    - [x] Increment cabal version
    - [x] Run `devtools.js -u`
    - New examples
        - [x] Add to cabal config
        - [x] Add to run-all-examples.sh
    - Prerelease
        - [x] Check if GitHub actions is successful
        - [x] Run `devtools.js -p`
- [x] Create release tag
